{{- if (and (.Values.ingress.enabled) (not .Values.openshift)) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gorge
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gorge
            port:
              name: http
{{- end }}
