{{- if (and (.Values.ingress.enabled) (.Values.openshift)) }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gorge
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.ingress.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: gorge
{{- end }}
